exports.keywords = {
    "FullName": /(?<=<FullName>)(.*)(?=<\/FullName>)/g,
    "FirstName": /(?<=<FirstName>)(.*)(?=<\/FirstName>)/g,
    "LastName": /(?<=<LastName>)(.*)(?=<\/LastName>)/g,
    "ContactInfo": /(?<=<ContactInfo>)(.*)(?=<\/ContactInfo>)/g,
    "Gender": /(?<=<Gender>)(.*)(?=<\/Gender>)/g,
    "District": /(?<=<District>)(.*)(?=<\/District>)/g,
    "subscriberNo":/(?<=<subscriberNo>)(.*)(?=<\/subscriberNo>)/g,
    "SubscriberNo":/(?<=<SubscriberNo>)(.*)(?=<\/SubscriberNo>)/g,
    "CustomerNo":/(?<=<CustomerNo>)(.*)(?=<\/CustomerNo>)/g,
    "CustomerName":/(?<=<CustomerName>)(.*)(?=<\/CustomerName>)/g,
    "CustomerContactNumber":/(?<=<CustomerContactNumber>)(.*)(?=<\/CustomerContactNumber>)/g,
    "CustomerAccountNumber":/(?<=<CustomerAccountNumber>)(.*)(?=<\/CustomerAccountNumber>)/g,
    "NS1:CustomerNo":/(?<=<NS1:CustomerNo>)(.*)(?=<\/NS1:CustomerNo>)/g,
    "Authorization":/(?<=<Authorization>)(.*)(?=<\/Authorization>)/g,
    "headers":/(?<=<headers.>)(.*)(?=<\/headers.>)/g,
    "serviceNumber":/(?<=<serviceNumber>)(.*)(?=<\/serviceNumber>)/g,
    "callerId":/(?<=<callerId>)(.*)(?=<\/callerId>)/g,
    "callerPassword":/(?<=<callerPassword>)(.*)(?=<\/callerPassword>)/g,
    "username":/(?<=<username>)(.*)(?=<\/username>)/g,
    "Username":/(?<=<Username>)(.*)(?=<\/Username>)/g,
    "U":/(?<=<U>)(.*)(?=<\/U>)/g,
    "P":/(?<=<P>)(.*)(?=<\/P>)/g,
    "wsse:Username":/(?<=<wsse:Username>)(.*)(?=<\/wsse:Username>)/g,
    "password":/(?<=<password>)(.*)(?=<\/password>)/g,
    "wsse:Password":/(?<=<wsse:Password)(.*)(?=<\/wsse:Password>)/g,
    "Password":/(?<=<Password>)(.*)(?=<\/Password>)/g,
    "fullphone":/(?<=<fullphone>)(.*)(?=<\/fullphone>)/g,
    "FullPhone":/(?<=<FullPhone>)(.*)(?=<\/FullPhone>)/g,
    "PhoneNumber":/(?<=<PhoneNumber>)(.*)(?=<\/PhoneNumber>)/g,
    "adslNumber":/(?<=<adslNumber>)(.*)(?=<\/adslNumber>)/g,
    "hostname":/(?<=<hostname>)(.*)(?=<\/hostname>)/g,
    "port":/(?<=<port>)(.*)(?=<\/port>)/g,
    "host":/(?<=<host>)(.*)(?=<\/host>)/g,
    "Followup_Number":/(?<=<Followup_Number>)(.*)(?=<\/Followup_Number>)/g,
    "followup_Number":/(?<=<followup_Number>)(.*)(?=<\/followup_Number>)/g,
    "tem:ServiceNumber": /(?<=<tem:ServiceNumber>)(.*)(?=<\/tem:ServiceNumber>)/g,
    "CallerId": /(?<=<CallerId>)(.*)(?=<\/CallerId>)/g,
    "CallerPassword": /(?<=<CallerPassword>)(.*)(?=<\/CallerPassword>)/g,
    "authkey": /(?<=<authkey>)(.*)(?=<\/authkey>)/g,
}